name: deploying
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: install dependencies
        run: npm ci
      - name: lint the code
        run: npm run lint
      - name: test the code
        run: npm run test
      - name: build the code
        run: npm run build
      - name: deployed the code
        run: echo "deployed"
        env:
            DISABLE_ESLINT_PLUGIN: true